
import fs from 'fs';
import path from 'path';
import {
  User,
  MenuItem,
  Table,
  Order,
  Reservation,
  Bill,
  Customer,
  CafeSettings,
} from '@/types';
import { hashPassword } from './auth';

export interface DatabaseSchema {
  users: User[];
  menuItems: MenuItem[];
  tables: Table[];
  orders: Order[];
  reservations: Reservation[];
  bills: Bill[];
  customers: Customer[];
  settings: CafeSettings;
}

const DATA_DIR = path.join(process.cwd(), 'data');
const DB_FILE = path.join(DATA_DIR, 'database.json');

// Realistic Initial Seed Data
const initialSettings: CafeSettings = {
  name: 'NOIR & BEAN',
  tagline: 'Coffee. Cuisine. Conversations.',
  address: '42 Heritage Boulevard, Bandra West, Mumbai, MH 400050',
  phone: '+91 98200 44921',
  email: 'concierge@noirandbean.com',
  gstin: '27AABCU9603R1ZM',
  cgstRate: 2.5,
  sgstRate: 2.5,
  currency: '₹',
  openingHours: [
    { days: 'Monday – Friday', hours: '08:00 AM – 11:30 PM' },
    { days: 'Saturday – Sunday', hours: '07:30 AM – 12:00 AM' },
  ],
};

const initialUsers: User[] = [
  {
    id: 'usr_admin',
    name: 'Alexander Vance',
    email: 'admin@noirandbean.com',
    passwordHash: hashPassword('admin123'),
    role: 'ADMIN',
    avatar: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?auto=format&fit=crop&w=400&q=80',
    phone: '+91 98200 11001',
    createdAt: '2026-01-10T10:00:00Z',
  },
  {
    id: 'usr_manager',
    name: 'Elena Rostova',
    email: 'manager@noirandbean.com',
    passwordHash: hashPassword('manager123'),
    role: 'MANAGER',
    avatar: 'https://images.unsplash.com/photo-1580489944761-15a19d654956?auto=format&fit=crop&w=400&q=80',
    phone: '+91 98200 11002',
    createdAt: '2026-01-15T11:00:00Z',
  },
  {
    id: 'usr_staff',
    name: 'Julian Hayes',
    email: 'staff@noirandbean.com',
    passwordHash: hashPassword('staff123'),
    role: 'STAFF',
    avatar: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?auto=format&fit=crop&w=400&q=80',
    phone: '+91 98200 11003',
    createdAt: '2026-02-01T09:00:00Z',
  },
];

const initialMenuItems: MenuItem[] = [
  // COFFEE
  {
    id: 'menu_01',
    name: 'Signature Smoked Sea Salt Cortado',
    description: 'Double ristretto infused with house-smoked Madagascar sea salt and micro-foamed silky oat emulsion.',
    category: 'Coffee',
    price: 340,
    image: 'https://images.unsplash.com/photo-1514432324607-a09d9b4aefdd?auto=format&fit=crop&w=800&q=80',
    isVeg: true,
    isPopular: true,
    isAvailable: true,
    preparationTime: 6,
    calories: 120,
  },
  {
    id: 'menu_02',
    name: 'Ethiopian Yirgacheffe V60 Pour-Over',
    description: 'Single-origin heirloom varietal offering delicate notes of bergamot, jasmine blossom, and candied stone fruit.',
    category: 'Coffee',
    price: 390,
    image: 'https://images.unsplash.com/photo-1544787219-7f47ccb76574?auto=format&fit=crop&w=800&q=80',
    isVeg: true,
    isPopular: true,
    isAvailable: true,
    preparationTime: 8,
    calories: 15,
  },
  {
    id: 'menu_03',
    name: 'Velvet Charcoal Latte',
    description: 'Activated organic coconut shell charcoal, raw honeycomb reduction, and steam-stretched Jersey milk.',
    category: 'Coffee',
    price: 380,
    image: 'https://images.unsplash.com/photo-1534778101976-62847782c213?auto=format&fit=crop&w=800&q=80',
    isVeg: true,
    isPopular: false,
    isAvailable: true,
    preparationTime: 7,
    calories: 145,
  },
  {
    id: 'menu_04',
    name: 'Kyoto 18-Hour Slow Drip Cold Brew',
    description: 'Cold extracted over single-estate Arabica beans through cold distilled ice towers. Finished with orange oil peel.',
    category: 'Coffee',
    price: 420,
    image: 'https://images.unsplash.com/photo-1517701550927-30cf4ba1dba5?auto=format&fit=crop&w=800&q=80',
    isVeg: true,
    isPopular: true,
    isAvailable: true,
    preparationTime: 4,
    calories: 10,
  },

  // TEA
  {
    id: 'menu_05',
    name: 'Ceremonial Uji Matcha Latte',
    description: 'First-harvest stone-ground matcha from Kyoto with subtle umami, paired with steamed almond milk and agave.',
    category: 'Tea',
    price: 410,
    image: 'https://images.unsplash.com/photo-1536256263959-770b48d82b0a?auto=format&fit=crop&w=800&q=80',
    isVeg: true,
    isPopular: true,
    isAvailable: true,
    preparationTime: 6,
    calories: 130,
  },
  {
    id: 'menu_06',
    name: 'Silver Needle Imperial White Tea',
    description: 'Rare hand-plucked spring bud tea with whisper-soft floral nectar aroma and lingering honey finish.',
    category: 'Tea',
    price: 360,
    image: 'https://images.unsplash.com/photo-1576092768241-dec231879fc3?auto=format&fit=crop&w=800&q=80',
    isVeg: true,
    isPopular: false,
    isAvailable: true,
    preparationTime: 5,
    calories: 5,
  },
  {
    id: 'menu_07',
    name: 'Smoked Saffron Masala Chai',
    description: 'Slow-simmered Assam orthodox blend with crushed green cardamom, Kashmiri saffron strands, and whole spices.',
    category: 'Tea',
    price: 290,
    image: 'https://images.unsplash.com/photo-1561336313-0bd5e0b27ec8?auto=format&fit=crop&w=800&q=80',
    isVeg: true,
    isPopular: true,
    isAvailable: true,
    preparationTime: 7,
    calories: 160,
  },

  // COLD BEVERAGES
  {
    id: 'menu_08',
    name: 'Yuzu Botanical Sparkler',
    description: 'Japanese yuzu cold reduction, bruised rosemary, pink peppercorns, and premium Mediterranean tonic.',
    category: 'Cold Beverages',
    price: 360,
    image: 'https://images.unsplash.com/photo-1513558161293-cdaf765ed2fd?auto=format&fit=crop&w=800&q=80',
    isVeg: true,
    isPopular: false,
    isAvailable: true,
    preparationTime: 5,
    calories: 95,
  },
  {
    id: 'menu_09',
    name: 'Cold-Pressed Valencia Blood Orange & Ginger',
    description: 'Freshly pressed sun-drenched blood oranges, organic ginger root, and sparkling mineral water over hand-cut ice.',
    category: 'Cold Beverages',
    price: 340,
    image: 'https://images.unsplash.com/photo-1613478223719-2ab802602423?auto=format&fit=crop&w=800&q=80',
    isVeg: true,
    isPopular: false,
    isAvailable: true,
    preparationTime: 4,
    calories: 110,
  },

  // BREAKFAST
  {
    id: 'menu_10',
    name: 'Truffled Wild Mushroom Tartine',
    description: 'Sauteed morel and chanterelle mushrooms on toasted rustic sourdough with herb whipped ricotta and black truffle oil.',
    category: 'Breakfast',
    price: 520,
    image: 'https://images.unsplash.com/photo-1525351484163-7529414344d8?auto=format&fit=crop&w=800&q=80',
    isVeg: true,
    isPopular: true,
    isAvailable: true,
    preparationTime: 14,
    calories: 410,
  },
  {
    id: 'menu_11',
    name: 'Avocado Tartine with Soft Poached Organic Eggs',
    description: 'Hass avocado puree, slow-poached eggs, toasted dukkah crunch, pickled shallots, and cold-pressed olive oil.',
    category: 'Breakfast',
    price: 540,
    image: 'https://images.unsplash.com/photo-1541519227354-08fa5d50c44d?auto=format&fit=crop&w=800&q=80',
    isVeg: false,
    isPopular: true,
    isAvailable: true,
    preparationTime: 12,
    calories: 460,
  },
  {
    id: 'menu_12',
    name: 'Almond French Brioche with Berry Coulis',
    description: 'Cultured butter brioche soaked in Tahitian vanilla custard, crowned with roasted almond flakes and fresh berries.',
    category: 'Breakfast',
    price: 490,
    image: 'https://images.unsplash.com/photo-1484723091739-30a097e8f929?auto=format&fit=crop&w=800&q=80',
    isVeg: true,
    isPopular: false,
    isAvailable: true,
    preparationTime: 15,
    calories: 520,
  },

  // SNACKS
  {
    id: 'menu_13',
    name: 'Artisan Burrata & Heirloom Tomato Carpaccio',
    description: 'Fresh Pugliese burrata, marinated heirloom tomatoes, basil oil infusion, 12-year Modena balsamic drizzle.',
    category: 'Snacks',
    price: 580,
    image: 'https://images.unsplash.com/photo-1592417817098-8f3d6eb2252a?auto=format&fit=crop&w=800&q=80',
    isVeg: true,
    isPopular: true,
    isAvailable: true,
    preparationTime: 10,
    calories: 380,
  },
  {
    id: 'menu_14',
    name: 'Crispy Saffron & Manchego Arancini',
    description: 'Crispy golden saffron risotto balls stuffed with aged Spanish Manchego cheese, served with smoked tomato sugo.',
    category: 'Snacks',
    price: 480,
    image: 'https://images.unsplash.com/photo-1541529086526-db283c563270?auto=format&fit=crop&w=800&q=80',
    isVeg: true,
    isPopular: false,
    isAvailable: true,
    preparationTime: 12,
    calories: 420,
  },
  {
    id: 'menu_15',
    name: 'Herbed Garlic Focaccia with Cultured Truffle Butter',
    description: 'Freshly baked overnight-fermented focaccia studded with rosemary and flaky fleur de sel, served warm.',
    category: 'Snacks',
    price: 360,
    image: 'https://images.unsplash.com/photo-1586444248902-2f64eddc13df?auto=format&fit=crop&w=800&q=80',
    isVeg: true,
    isPopular: false,
    isAvailable: true,
    preparationTime: 8,
    calories: 340,
  },

  // MAIN COURSE
  {
    id: 'menu_16',
    name: 'Handcrafted Truffle & Wild Mushroom Pappardelle',
    description: 'Fresh handmade pasta ribbons tossed in white truffle emulsion, pan-glazed shiitake, and 24-month Parmigiano-Reggiano.',
    category: 'Main Course',
    price: 740,
    image: 'https://images.unsplash.com/photo-1621996346565-e3d5d6281223?auto=format&fit=crop&w=800&q=80',
    isVeg: true,
    isPopular: true,
    isAvailable: true,
    preparationTime: 18,
    calories: 590,
  },
  {
    id: 'menu_17',
    name: 'Rosemary Sous-Vide Chicken Breast with Gnocchi',
    description: 'Tender free-range chicken supreme, pan-crisped potato gnocchi, braised leeks, and roasted garlic poultry jus.',
    category: 'Main Course',
    price: 790,
    image: 'https://images.unsplash.com/photo-1604908176997-125f25cc6f3d?auto=format&fit=crop&w=800&q=80',
    isVeg: false,
    isPopular: true,
    isAvailable: true,
    preparationTime: 20,
    calories: 640,
  },
  {
    id: 'menu_18',
    name: 'Pan-Seared Chilean Sea Bass with Veloute',
    description: 'Sustainably caught sea bass fillet over saffron-scented crushed potatoes, wilted baby spinach, and lemon caper emulsion.',
    category: 'Main Course',
    price: 980,
    image: 'https://images.unsplash.com/photo-1519708227418-c8fd9a32b7a2?auto=format&fit=crop&w=800&q=80',
    isVeg: false,
    isPopular: true,
    isAvailable: true,
    preparationTime: 22,
    calories: 560,
  },
  {
    id: 'menu_19',
    name: 'Smoked Sourdough Brioche Burger with Gruyère',
    description: 'Caramelized onion jam, aged melted Gruyère, crisp bibb lettuce, and house grain-mustard aioli with truffle fries.',
    category: 'Main Course',
    price: 680,
    image: 'https://images.unsplash.com/photo-1568901346375-23c9450c58cd?auto=format&fit=crop&w=800&q=80',
    isVeg: false,
    isPopular: true,
    isAvailable: true,
    preparationTime: 16,
    calories: 780,
  },

  // DESSERTS
  {
    id: 'menu_20',
    name: 'San Sebastián Basque Burnt Cheesecake',
    description: 'Caramelized caramelized exterior with an impossibly molten, silky cream center. Served with sour cherry compote.',
    category: 'Desserts',
    price: 450,
    image: 'https://images.unsplash.com/photo-1533134242443-d4fd215305ad?auto=format&fit=crop&w=800&q=80',
    isVeg: true,
    isPopular: true,
    isAvailable: true,
    preparationTime: 5,
    calories: 480,
  },
  {
    id: 'menu_21',
    name: 'Classic Dark Chocolate Valrhona Tart',
    description: '70% Guanaja single-origin chocolate ganache in crisp cocoa sable shell, topped with gold leaf and sea salt flakes.',
    category: 'Desserts',
    price: 480,
    image: 'https://images.unsplash.com/photo-1579372786545-d24232daf58c?auto=format&fit=crop&w=800&q=80',
    isVeg: true,
    isPopular: true,
    isAvailable: true,
    preparationTime: 5,
    calories: 510,
  },
  {
    id: 'menu_22',
    name: 'Tiramisù Al Caffè Espresso',
    description: 'House-baked savoiardi soaked in our 18-hour cold brew, folded with light mascarpone sabayon and raw cacao.',
    category: 'Desserts',
    price: 460,
    image: 'https://images.unsplash.com/photo-1571877227200-a0d98ea607e9?auto=format&fit=crop&w=800&q=80',
    isVeg: true,
    isPopular: false,
    isAvailable: true,
    preparationTime: 5,
    calories: 440,
  },

  // SPECIALS
  {
    id: 'menu_23',
    name: 'Chef’s Gold Leaf Opera Gateau',
    description: 'Almond sponge steeped in Grand Cru espresso, dark chocolate ganache, French coffee buttercream, and 24K edible gold.',
    category: 'Specials',
    price: 620,
    image: 'https://images.unsplash.com/photo-1587314168485-3236d6710814?auto=format&fit=crop&w=800&q=80',
    isVeg: true,
    isPopular: true,
    isAvailable: true,
    preparationTime: 6,
    calories: 550,
  },
  {
    id: 'menu_24',
    name: 'Caviar & Crème Fraîche Brioche Toast',
    description: 'Toasted brioche fingers topped with Normandy cultured crème fraîche, royal Oscietra caviar, and micro chives.',
    category: 'Specials',
    price: 1250,
    image: 'https://images.unsplash.com/photo-1504674900247-0877df9cc836?auto=format&fit=crop&w=800&q=80',
    isVeg: false,
    isPopular: false,
    isAvailable: true,
    preparationTime: 10,
    calories: 280,
  },
];

const initialTables: Table[] = [
  {
    id: 'tbl_01',
    number: '01',
    name: 'Table 01',
    capacity: 2,
    section: 'Window',
    status: 'Available',
  },
  {
    id: 'tbl_02',
    number: '02',
    name: 'Table 02',
    capacity: 2,
    section: 'Window',
    status: 'Occupied',
    currentOrderId: 'ord_102',
    currentBillAmount: 850,
  },
  {
    id: 'tbl_03',
    number: '03',
    name: 'Table 03',
    capacity: 4,
    section: 'Indoor',
    status: 'Reserved',
    currentReservationId: 'res_001',
  },
  {
    id: 'tbl_04',
    number: '04',
    name: 'Table 04',
    capacity: 4,
    section: 'Indoor',
    status: 'Available',
  },
  {
    id: 'tbl_05',
    number: '05',
    name: 'Table 05',
    capacity: 6,
    section: 'Indoor',
    status: 'Occupied',
    currentOrderId: 'ord_104',
    currentBillAmount: 1840,
  },
  {
    id: 'tbl_06',
    number: '06',
    name: 'Table 06',
    capacity: 2,
    section: 'Patio',
    status: 'Available',
  },
  {
    id: 'tbl_07',
    number: '07',
    name: 'Table 07',
    capacity: 4,
    section: 'Patio',
    status: 'Billing',
    currentOrderId: 'ord_105',
    currentBillAmount: 1220,
  },
  {
    id: 'tbl_08',
    number: '08',
    name: 'Table 08',
    capacity: 4,
    section: 'Patio',
    status: 'Available',
  },
  {
    id: 'tbl_09',
    number: '09',
    name: 'Table 09',
    capacity: 8,
    section: 'Private',
    status: 'Cleaning',
  },
  {
    id: 'tbl_10',
    number: '10',
    name: 'Table 10',
    capacity: 6,
    section: 'Private',
    status: 'Available',
  },
];

const initialOrders: Order[] = [
  {
    id: 'ord_101',
    orderNumber: 'NB-7291',
    customerName: 'Aarav Mehta',
    customerPhone: '+91 98331 44520',
    customerEmail: 'aarav.mehta@example.com',
    type: 'dine-in',
    tableId: 'tbl_01',
    tableNumber: '01',
    items: [
      {
        menuItemId: 'menu_01',
        name: 'Signature Smoked Sea Salt Cortado',
        price: 340,
        quantity: 2,
        isVeg: true,
        image: 'https://images.unsplash.com/photo-1514432324607-a09d9b4aefdd?auto=format&fit=crop&w=800&q=80',
      },
      {
        menuItemId: 'menu_10',
        name: 'Truffled Wild Mushroom Tartine',
        price: 520,
        quantity: 1,
        isVeg: true,
        image: 'https://images.unsplash.com/photo-1525351484163-7529414344d8?auto=format&fit=crop&w=800&q=80',
      },
    ],
    subtotal: 1200,
    discountAmount: 0,
    cgst: 30,
    sgst: 30,
    grandTotal: 1260,
    status: 'Ready',
    paymentStatus: 'Paid',
    paymentMethod: 'UPI',
    createdAt: new Date(Date.now() - 35 * 60 * 1000).toISOString(),
    updatedAt: new Date(Date.now() - 5 * 60 * 1000).toISOString(),
  },
  {
    id: 'ord_102',
    orderNumber: 'NB-7292',
    customerName: 'Pooja Singhania',
    customerPhone: '+91 97690 88214',
    customerEmail: 'pooja.s@example.com',
    type: 'dine-in',
    tableId: 'tbl_02',
    tableNumber: '02',
    items: [
      {
        menuItemId: 'menu_05',
        name: 'Ceremonial Uji Matcha Latte',
        price: 410,
        quantity: 1,
        isVeg: true,
        image: 'https://images.unsplash.com/photo-1536256263959-770b48d82b0a?auto=format&fit=crop&w=800&q=80',
      },
      {
        menuItemId: 'menu_20',
        name: 'San Sebastián Basque Burnt Cheesecake',
        price: 450,
        quantity: 1,
        isVeg: true,
        image: 'https://images.unsplash.com/photo-1533134242443-d4fd215305ad?auto=format&fit=crop&w=800&q=80',
      },
    ],
    subtotal: 860,
    discountAmount: 0,
    cgst: 21.5,
    sgst: 21.5,
    grandTotal: 903,
    status: 'Preparing',
    paymentStatus: 'Pending',
    createdAt: new Date(Date.now() - 15 * 60 * 1000).toISOString(),
    updatedAt: new Date(Date.now() - 10 * 60 * 1000).toISOString(),
  },
  {
    id: 'ord_103',
    orderNumber: 'NB-7293',
    customerName: 'Karan Oberoi',
    customerPhone: '+91 99201 55678',
    customerEmail: 'karan.o@example.com',
    type: 'takeaway',
    pickupTime: '15 Mins',
    items: [
      {
        menuItemId: 'menu_04',
        name: 'Kyoto 18-Hour Slow Drip Cold Brew',
        price: 420,
        quantity: 1,
        isVeg: true,
        image: 'https://images.unsplash.com/photo-1517701550927-30cf4ba1dba5?auto=format&fit=crop&w=800&q=80',
      },
      {
        menuItemId: 'menu_11',
        name: 'Avocado Tartine with Soft Poached Organic Eggs',
        price: 540,
        quantity: 1,
        isVeg: false,
        image: 'https://images.unsplash.com/photo-1541519227354-08fa5d50c44d?auto=format&fit=crop&w=800&q=80',
      },
    ],
    subtotal: 960,
    discountAmount: 0,
    cgst: 24,
    sgst: 24,
    grandTotal: 1008,
    status: 'Pending',
    paymentStatus: 'Pending',
    createdAt: new Date(Date.now() - 5 * 60 * 1000).toISOString(),
    updatedAt: new Date(Date.now() - 5 * 60 * 1000).toISOString(),
  },
  {
    id: 'ord_104',
    orderNumber: 'NB-7294',
    customerName: 'Natasha Kapoor',
    customerPhone: '+91 98199 44321',
    customerEmail: 'natasha.k@example.com',
    type: 'dine-in',
    tableId: 'tbl_05',
    tableNumber: '05',
    items: [
      {
        menuItemId: 'menu_16',
        name: 'Handcrafted Truffle & Wild Mushroom Pappardelle',
        price: 740,
        quantity: 2,
        isVeg: true,
        image: 'https://images.unsplash.com/photo-1621996346565-e3d5d6281223?auto=format&fit=crop&w=800&q=80',
      },
      {
        menuItemId: 'menu_08',
        name: 'Yuzu Botanical Sparkler',
        price: 360,
        quantity: 1,
        isVeg: true,
        image: 'https://images.unsplash.com/photo-1513558161293-cdaf765ed2fd?auto=format&fit=crop&w=800&q=80',
      },
    ],
    subtotal: 1840,
    discountAmount: 0,
    cgst: 46,
    sgst: 46,
    grandTotal: 1932,
    status: 'Preparing',
    paymentStatus: 'Pending',
    createdAt: new Date(Date.now() - 22 * 60 * 1000).toISOString(),
    updatedAt: new Date(Date.now() - 15 * 60 * 1000).toISOString(),
  },
];

const initialReservations: Reservation[] = [
  {
    id: 'res_001',
    reservationNumber: 'RES-8901',
    customerName: 'Rohan Deshmukh',
    customerPhone: '+91 98210 33499',
    customerEmail: 'rohan.d@example.com',
    date: new Date().toISOString().split('T')[0],
    time: '20:00',
    guests: 4,
    tablePreference: 'Indoor',
    specialRequests: 'Anniversary celebration, romantic ambient corner preferred.',
    status: 'Confirmed',
    assignedTableId: 'tbl_03',
    assignedTableNumber: '03',
    createdAt: new Date(Date.now() - 4 * 3600 * 1000).toISOString(),
  },
  {
    id: 'res_002',
    reservationNumber: 'RES-8902',
    customerName: 'Ananya Roy',
    customerPhone: '+91 97110 55432',
    customerEmail: 'ananya.roy@example.com',
    date: new Date().toISOString().split('T')[0],
    time: '21:30',
    guests: 2,
    tablePreference: 'Patio',
    specialRequests: 'Outdoor seating under canopy.',
    status: 'Pending',
    createdAt: new Date(Date.now() - 2 * 3600 * 1000).toISOString(),
  },
  {
    id: 'res_003',
    reservationNumber: 'RES-8903',
    customerName: 'Devang Vora',
    customerPhone: '+91 98205 66789',
    customerEmail: 'devang.v@example.com',
    date: new Date(Date.now() + 86400000).toISOString().split('T')[0],
    time: '19:00',
    guests: 6,
    tablePreference: 'Private',
    specialRequests: 'Business dinner, privacy requested.',
    status: 'Confirmed',
    assignedTableId: 'tbl_10',
    assignedTableNumber: '10',
    createdAt: new Date(Date.now() - 12 * 3600 * 1000).toISOString(),
  },
];

const initialCustomers: Customer[] = [
  {
    id: 'cust_01',
    name: 'Aarav Mehta',
    phone: '+91 98331 44520',
    email: 'aarav.mehta@example.com',
    totalOrders: 6,
    totalSpend: 7540,
    lastVisit: 'Today',
    notes: 'Prefers oat milk cortado. Member of Coffee Circle.',
  },
  {
    id: 'cust_02',
    name: 'Pooja Singhania',
    phone: '+91 97690 88214',
    email: 'pooja.s@example.com',
    totalOrders: 9,
    totalSpend: 11420,
    lastVisit: 'Today',
    notes: 'Loves Basque burnt cheesecake and Matcha.',
  },
  {
    id: 'cust_03',
    name: 'Rohan Deshmukh',
    phone: '+91 98210 33499',
    email: 'rohan.d@example.com',
    totalOrders: 4,
    totalSpend: 6200,
    lastVisit: 'Yesterday',
    notes: 'Frequent dinner reservations on weekends.',
  },
  {
    id: 'cust_04',
    name: 'Natasha Kapoor',
    phone: '+91 98199 44321',
    email: 'natasha.k@example.com',
    totalOrders: 12,
    totalSpend: 19850,
    lastVisit: 'Today',
    notes: 'VIP guest. Handcrafted pasta connoisseur.',
  },
];

const initialBills: Bill[] = [
  {
    id: 'bill_001',
    invoiceNumber: 'INV-2026-081',
    orderId: 'ord_101',
    orderNumber: 'NB-7291',
    tableNumber: '01',
    customerName: 'Aarav Mehta',
    customerPhone: '+91 98331 44520',
    items: initialOrders[0].items,
    subtotal: 1200,
    discountPercentage: 0,
    discountAmount: 0,
    cgst: 30,
    sgst: 30,
    grandTotal: 1260,
    paymentMethod: 'UPI',
    paymentStatus: 'Paid',
    generatedAt: new Date(Date.now() - 10 * 60 * 1000).toISOString(),
    gstin: '27AABCU9603R1ZM',
  },
];

export function getDb(): DatabaseSchema {
  if (!fs.existsSync(DATA_DIR)) {
    fs.mkdirSync(DATA_DIR, { recursive: true });
  }

  if (!fs.existsSync(DB_FILE)) {
    const seed: DatabaseSchema = {
      users: initialUsers,
      menuItems: initialMenuItems,
      tables: initialTables,
      orders: initialOrders,
      reservations: initialReservations,
      bills: initialBills,
      customers: initialCustomers,
      settings: initialSettings,
    };
    fs.writeFileSync(DB_FILE, JSON.stringify(seed, null, 2), 'utf8');
    return seed;
  }

  try {
    const content = fs.readFileSync(DB_FILE, 'utf8');
    return JSON.parse(content);
  } catch {
    const seed: DatabaseSchema = {
      users: initialUsers,
      menuItems: initialMenuItems,
      tables: initialTables,
      orders: initialOrders,
      reservations: initialReservations,
      bills: initialBills,
      customers: initialCustomers,
      settings: initialSettings,
    };
    fs.writeFileSync(DB_FILE, JSON.stringify(seed, null, 2), 'utf8');
    return seed;
  }
}

export function saveDb(db: DatabaseSchema): void {
  if (!fs.existsSync(DATA_DIR)) {
    fs.mkdirSync(DATA_DIR, { recursive: true });
  }
  fs.writeFileSync(DB_FILE, JSON.stringify(db, null, 2), 'utf8');
}
